const makeLesson=(id,week,day,title,concept,explanation,analogy,visual,recognize,apply,assignment,type='lesson')=>({
  id,course:'S0',week,day,title,concept,type,duration:type==='exam'?'90–120 minutes':'60 minutes',
  objective:`Understand ${title.toLowerCase()} and demonstrate the idea through explanation, recognition, and application.`,
  theory:explanation,intuition:analogy,visual,
  part1:{
    title:'Build the core model',time:'About 20 minutes',
    explanation,
    guidance:`Read slowly, connect the explanation to the mental model, and say the three-step sequence aloud. Focus on what changes from ${visual[0].toLowerCase()} to ${visual[2].toLowerCase()}.`
  },
  checkpoint1:{question:recognize.question,options:recognize.options,answer:recognize.answer,explanation:recognize.explanation},
  part2:{
    title:'Connect the model to practice',time:'About 20 minutes',
    explanation:`Now move from recognizing the term to using it. The practical task for this concept is: ${apply} A strong application identifies the situation, follows the model in order, and checks whether the result matches the goal.`,
    guidance:`Use this sequence as your internal checklist: ${visual.join(' → ')}. Compare a correct use of the concept with a weak use that skips one of these steps.`
  },
  checkpoint2:{
    question:`Which sequence correctly represents the mental model for ${title.toLowerCase()}?`,
    options:[visual.join(' → '),[visual[2],visual[1],visual[0]].join(' → '),`${visual[0]} → skip the middle step → ${visual[2]}`],
    answer:0,explanation:`The lesson model follows this order: ${visual.join(' → ')}.`
  },
  prompt:`Without looking back, explain ${title.toLowerCase()} in your own words and state why it matters.`,
  recognize:{question:recognize.question,options:recognize.options,answer:recognize.answer,explanation:recognize.explanation},
  apply:{prompt:apply},
  assignment:{title:assignment.title,instructions:assignment.instructions},
  homework:{title:assignment.title,instructions:assignment.instructions,estimatedTime:type==='exam'?'45–90 minutes':'20–40 minutes'},
  resources:['r-original-s0']
});

window.S0_LESSONS=[
makeLesson('S0-W1-O',1,'Orientation','How the Academy proves understanding','active-recall',
  'Reading a correct explanation can create familiarity without proving recall or application. A concept becomes Mastered only after evidence shows that you can explain it, recognize it in a new situation, and apply it to a focused problem.',
  'Seeing a volleyball coach demonstrate a serve is not the same as reproducing the serve under pressure. Learning evidence works the same way.',
  ['Read / Observe','Retrieve without looking','Apply / Explain'],
  {question:'Which action provides the strongest evidence of active recall?',options:['Rereading a definition three times','Closing the lesson and explaining the idea from memory','Highlighting the most important sentence'],answer:1,explanation:'Retrieving the idea without seeing it tests what is available in memory.'},
  'Describe one change you will make to turn a familiar idea from class into something you can retrieve and use.',
  {title:'Learning evidence statement',instructions:'Write 3–5 sentences explaining how you will prove understanding in this Academy.'}),

makeLesson('S0-W1-D1',1,'Monday','Academy setup and identity: Engineer in Training','learning-system',
  'An engineer in training does not wait to know everything before behaving systematically. You create a repeatable place for lessons, assignments, exams, projects, feedback, and reflection so evidence does not disappear across apps or notebooks.',
  'A volleyball team improves faster when equipment, rotations, statistics, and practice plans have consistent homes. Your learning needs the same operational discipline.',
  ['Create structure','Use consistently','Review evidence'],
  {question:'Which setup best supports long-term engineering study?',options:['Saving files wherever there is space','Keeping one consistent course and evidence structure','Depending on browser history to find work'],answer:1,explanation:'A consistent structure makes work retrievable, reviewable, and durable.'},
  'List the exact places where you will keep lessons, assignments, exams, projects, and reflections.',
  {title:'Build the Academy workspace',instructions:'Create the approved folder structure, save the dashboard, and confirm where the Handbook will live.'}),

makeLesson('S0-W1-D2',1,'Tuesday','How engineers learn','learning-cycle',
  'Engineering learning is a cycle: encounter theory, try to build or solve, become stuck, inspect evidence, revise the mental model, and try again. Getting stuck is information about the model—not proof that you cannot learn the subject.',
  'A serve improves through demonstration, attempts, errors, feedback, and another attempt. Reading about serving cannot replace the cycle.',
  ['Learn','Attempt + error','Revise + retry'],
  {question:'What should happen after an engineering attempt fails?',options:['Hide the failure and start a new topic','Inspect what happened, revise the model, and retry','Memorize the final answer without tracing the cause'],answer:1,explanation:'Failure becomes useful when it changes the next attempt.'},
  'Describe a recent technical mistake and identify what you would inspect before trying again.',
  {title:'How I learn best',instructions:'Write a one-page reflection describing how you currently learn, what helps, and what usually causes you to stop.'}),

makeLesson('S0-W1-D3',1,'Wednesday','Active recall and why rereading is weak','active-recall',
  'Rereading presents the answer to the brain; active recall asks the brain to reconstruct it. Retrieval exposes missing pieces, strengthens access to the idea, and gives you evidence about what needs review.',
  'Looking at the rotation sheet feels easier than calling the rotation correctly during a match. The match requires retrieval.',
  ['Study','Close source','Retrieve + check'],
  {question:'Which study action is active recall?',options:['Copying the paragraph word for word','Explaining the concept before reopening the notes','Reading the same page more slowly'],answer:1,explanation:'The explanation must be retrieved before the source supplies it.'},
  'Create one recall question for a current college class and answer it without notes.',
  {title:'Ten flash questions',instructions:'Create 10 questions from today’s lesson. Put answers on a separate page so you must retrieve before checking.'}),

makeLesson('S0-W1-D4',1,'Thursday','Mental models: understanding before memorizing','mental-model',
  'A mental model is a simplified internal explanation of how something works. It should help you predict behavior, not merely repeat vocabulary. Good models can be refined when new evidence reveals that they are incomplete.',
  'A subway map is not the city, but it preserves the relationships needed to plan a trip. A mental model does the same for a system.',
  ['Simplify system','Predict behavior','Revise model'],
  {question:'Which statement describes a useful mental model?',options:['An exact copy of every detail','A simplified explanation that supports predictions','A list of terms with no relationships'],answer:1,explanation:'The value of a model is that it preserves useful relationships and supports reasoning.'},
  'Choose a familiar system and explain it with a simple analogy, including one limitation of the analogy.',
  {title:'Analogy exercise',instructions:'Explain one concept using a real-life analogy, then identify where the analogy stops being accurate.'}),

makeLesson('S0-W1-D5',1,'Friday','Reflection system and weekly evidence','reflection',
  'Reflection converts activity into information for the next decision. Useful reflection is specific: what changed, what remains weak, what evidence exists, and what action should follow.',
  'A coach reviews game film to change the next practice plan—not simply to remember that a game happened.',
  ['Collect evidence','Name the gap','Choose next action'],
  {question:'Which reflection is most useful?',options:['I studied a lot','Loops are still confusing because I lose track of the counter; I will trace three examples','Everything was fine'],answer:1,explanation:'Specific evidence identifies both the problem and the next action.'},
  'Write one specific reflection about something you studied this week.',
  {title:'Sunday review folder',instructions:'Prepare notes, questions, attempts, and completed work for the weekly review.'}),

makeLesson('S0-W1-D6',1,'Saturday','Practice: organize notes and identify weak points','deliberate-practice',
  'Practice is most valuable when it targets a known weakness. Organizing evidence helps you distinguish unfinished work from concepts that genuinely require another explanation or attempt.',
  'A team does not spend every practice repeating its strongest rotation. It studies where points are being lost.',
  ['Inspect work','Find weak point','Practice deliberately'],
  {question:'What should determine the next practice task?',options:['The easiest activity available','A specific weakness shown by evidence','Whatever appears first in the folder'],answer:1,explanation:'Deliberate practice is selected from evidence of weakness.'},
  'Name one weak point from Week 1 and design a 10-minute practice activity for it.',
  {title:'Week 1 review questions',instructions:'Complete the Week 1 review and organize every submission before the weekly exam.'},'practice'),

makeLesson('S0-W1-D7',1,'Sunday','Weekly review and Paper Exam 0A','learning-evidence',
  'A closed paper exam tests what you can retrieve and reason through without assistance. The goal is honest evidence. A low result is diagnostic information used to plan remediation.',
  'Game day reveals which skills remain available under pressure after practice support is removed.',
  ['Prepare honestly','Retrieve independently','Review evidence'],
  {question:'Why must the exam conditions be followed exactly?',options:['To make the paper look official','So the result measures your independent knowledge','So every answer is automatically correct'],answer:1,explanation:'Changing the allowed support changes what the score measures.'},
  'State the exam conditions in your own words and explain what you will do if you do not know an answer.',
  {title:'Paper Exam 0A',instructions:'Print the exam workspace, complete it without AI, Google, an IDE, or notes unless explicitly allowed, then record the completion and reflection.'},'exam'),

makeLesson('S0-W2-D1',2,'Monday','What is computation?','computation',
  'Computation is the systematic transformation of information according to defined rules. A computer performs operations on representations of a problem; people decide what the problem means and whether the result is useful.',
  'A kitchen transforms ingredients into a dish by following operations. Computation transforms inputs into outputs through procedures.',
  ['Represent input','Follow operations','Produce output'],
  {question:'Which example is computation?',options:['A device transforms GPS coordinates into a route using rules','A notebook stays closed on a table','A screen displays an unplugged image'],answer:0,explanation:'The route system transforms represented inputs according to procedures.'},
  'Choose one app and identify the information it transforms.',
  {title:'Five computational problems',instructions:'Write five examples of problems computers solve and identify the information involved.'}),

makeLesson('S0-W2-D2',2,'Tuesday','Algorithms as instructions','algorithm',
  'An algorithm is a finite, ordered procedure for solving a class of problems. Good instructions identify required inputs, unambiguous steps, stopping conditions, and expected outputs.',
  'A recipe is algorithm-like when another person can follow the steps and know when the dish is finished.',
  ['Inputs','Ordered steps','Stop + output'],
  {question:'Which instruction is most algorithmic?',options:['Make it look good somehow','Repeat stirring until the timer reaches zero','Think about dinner'],answer:1,explanation:'It defines an action and a clear stopping condition.'},
  'Write an algorithm for checking whether you have everything needed before leaving home.',
  {title:'Daily-task algorithm',instructions:'Write and test an algorithm for one daily task. Revise any ambiguous step discovered during the test.'}),

makeLesson('S0-W2-D3',2,'Wednesday','Inputs and outputs','input-output',
  'An input is information or a signal supplied to a system. Processing transforms or uses it, and an output is the observable result. The same system can produce different outputs when its inputs or state change.',
  'A coffee machine receives water, coffee, a selection, and power; it produces a drink and status signals.',
  ['Input','Processing','Output'],
  {question:'In a navigation app, which item is an input?',options:['The calculated route','The destination entered by the user','The arrival notification'],answer:1,explanation:'The destination is supplied to the system before route calculation.'},
  'Map the inputs, processing, and outputs of one tool you use at work.',
  {title:'Five app maps',instructions:'Identify the inputs and outputs of five apps. Include at least one output that is not visual.'}),

makeLesson('S0-W2-D4',2,'Thursday','Variables as memory boxes','variable',
  'A variable is a named location or binding used to refer to a value that a program needs. The current value may change over time, while the name lets the program access the relevant information consistently.',
  'A labeled scoreboard space can hold the current score. The label remains while the number changes.',
  ['Name','Current value','Update'],
  {question:'What changes when score increases from 2 to 3?',options:['The variable name must disappear','The value associated with the variable changes','Every program instruction changes'],answer:1,explanation:'The variable continues to identify the score while its stored value changes.'},
  'Trace a variable named balance through a purchase and a refund.',
  {title:'Variable story',instructions:'Draw three variables changing through a simple story and label every update.'}),

makeLesson('S0-W2-D5',2,'Friday','Conditionals as decisions','conditional',
  'A conditional selects an action based on whether a test is true or false. It lets the same program respond differently to different data or states.',
  'A traffic light rule changes the driver’s action depending on the observed color.',
  ['Test condition','Choose branch','Perform action'],
  {question:'Which sentence expresses a conditional?',options:['The door is blue','If the password matches, allow access','Store the username'],answer:1,explanation:'It connects a test to an action.'},
  'Write an if/then rule for deciding whether a shop needs a follow-up.',
  {title:'Eight decisions',instructions:'Create eight if/then examples and identify the condition and resulting action in each.'}),

makeLesson('S0-W2-D6',2,'Saturday','Week 2 practice set','computational-thinking',
  'Computational thinking combines representation, decomposition, procedures, inputs and outputs, memory, and decisions. Practice should connect these pieces into one traceable system.',
  'A rotation plan connects players, positions, rules, and changing scores rather than treating each fact alone.',
  ['Describe problem','Trace information','Check result'],
  {question:'Which description shows systems thinking?',options:['The app is useful','The app receives an address, checks map data, calculates routes, and displays directions','The app has a blue icon'],answer:1,explanation:'It traces information through connected system stages.'},
  'Map a small system using input, variable, conditional, and output.',
  {title:'Week 2 practice',instructions:'Complete the computation, algorithm, input/output, variable, and conditional practice set.'},'practice'),

makeLesson('S0-W2-D7',2,'Sunday','Paper Exam 0B and mini project','computational-model',
  'This checkpoint tests whether you can describe small computational systems without relying on memorized wording. The mini project turns a daily process into a precise model.',
  'A scouting report becomes actionable only when observations are converted into decisions and planned responses.',
  ['Retrieve concepts','Model a process','Review result'],
  {question:'Which project contains a complete small-system model?',options:['A list of app colors','Inputs, ordered rules, state changes, and outputs for a task','A copied definition of algorithm'],answer:1,explanation:'A system model must connect the information and operations.'},
  'Outline a tool that solves one small personal or work problem.',
  {title:'Paper Exam 0B + mini project plan',instructions:'Complete the closed paper exam, then submit a one-page mini project problem and system outline.'},'exam'),

makeLesson('S0-W3-D1',3,'Monday','Loops as repetition with memory','loop',
  'A loop repeats a block of work while tracking enough state to know what changes and when to stop. A loop without a correct update or stopping condition may never finish.',
  'A serving drill repeats attempts while the coach counts repetitions and stops at the planned total.',
  ['Initialize state','Repeat + update','Stop'],
  {question:'What prevents a counting loop from running forever?',options:['A variable update and reachable stopping condition','A longer variable name','More comments'],answer:0,explanation:'The state must move toward a condition that ends repetition.'},
  'Trace a counter beginning at 1 and increasing until it reaches 5.',
  {title:'Five-iteration trace',instructions:'Trace one loop by hand for five iterations, recording state before and after every update.'}),

makeLesson('S0-W3-D2',3,'Tuesday','Loop tracing practice','loop-tracing',
  'Tracing means simulating code one step at a time and recording variable values. It exposes off-by-one errors, missing updates, and incorrect assumptions before execution hides the reasoning.',
  'A scorekeeper records every point rather than guessing the final score from memory.',
  ['Read condition','Record state','Execute update'],
  {question:'What should a tracing table record?',options:['Only the final output','Relevant values during each iteration','The programmer’s favorite line'],answer:1,explanation:'Iteration-by-iteration state reveals how the loop behaves.'},
  'Create column headings for tracing index and total through a loop.',
  {title:'Three tracing tables',instructions:'Complete three loop tracing tables and circle the exact iteration where each loop stops.'}),

makeLesson('S0-W3-D3',3,'Wednesday','Functions as reusable machines','function',
  'A function packages a defined responsibility behind a name. It may receive inputs, perform work, change state, and return an output. Clear boundaries make behavior easier to reuse and test.',
  'A blender has a recognizable interface: ingredients and a setting enter; blended food leaves.',
  ['Receive input','Perform responsibility','Return output'],
  {question:'Why create a function?',options:['To hide every program decision','To package a reusable responsibility with a clear interface','To guarantee that errors are impossible'],answer:1,explanation:'A function creates a named, reusable boundary around behavior.'},
  'Design a function named calculateTip and identify its input and output.',
  {title:'Five life functions',instructions:'Describe five functions you wish existed in daily life, including inputs, outputs, and responsibility.'}),

makeLesson('S0-W3-D4',3,'Thursday','Debugging mindset','debugging',
  'Debugging is evidence-driven investigation. Define expected behavior, observe actual behavior, identify where they first diverge, form a hypothesis, test one change, and record the result.',
  'A mechanic does not replace every car part at once; evidence narrows the failing system.',
  ['Expected vs actual','Locate divergence','Test hypothesis'],
  {question:'What is the best first debugging action?',options:['Change several things randomly','State what was expected and what actually happened','Delete the project'],answer:1,explanation:'The difference between expected and actual behavior defines the investigation.'},
  'Use expected, actual, evidence, and next check to describe today’s Save Attempt issue.',
  {title:'Debugging story',instructions:'Write a debugging story from your own computer issue using observations, hypothesis, test, and result.'}),

makeLesson('S0-W3-D5',3,'Friday','Syntax, runtime, and logic errors','error-type',
  'A syntax error violates language structure, a runtime error occurs while the program executes, and a logic error allows execution but produces the wrong behavior. Classification guides where to inspect first.',
  'A sentence can be grammatically malformed, impossible to carry out, or grammatically correct but factually wrong.',
  ['Parse','Execute','Validate result'],
  {question:'A program runs but calculates the wrong total. What type of error is most likely?',options:['Syntax error','Logic error','No error is possible'],answer:1,explanation:'Execution succeeds, but the reasoning produces an incorrect result.'},
  'Create one original example of each error type.',
  {title:'Classify ten errors',instructions:'Classify ten scenarios as syntax, runtime, or logic errors and explain two uncertain choices.'}),

makeLesson('S0-W3-D6',3,'Saturday','Week 3 practice set','program-tracing',
  'Tracing connects loops, variables, functions, and failures. The goal is to predict behavior before execution and use discrepancies as debugging evidence.',
  'A planned volleyball rotation is traced point by point to verify who should occupy each position.',
  ['Predict','Trace','Compare'],
  {question:'Why predict output before running code?',options:['To avoid ever using a computer','To compare your mental model with actual execution','To make the code longer'],answer:1,explanation:'The comparison reveals whether your model matches program behavior.'},
  'Trace a function call that contains a three-iteration loop.',
  {title:'Week 3 practice',instructions:'Complete the loop, function, tracing, debugging, and error-classification practice set.'},'practice'),

makeLesson('S0-W3-D7',3,'Sunday','Paper Exam 0C and guided build','debuggable-program',
  'A small build demonstrates whether concepts can work together. The artifact matters, but the stronger evidence is your ability to trace it, explain decisions, test behavior, and identify limitations.',
  'A completed play is useful; explaining why it worked makes the team able to repeat and improve it.',
  ['Build','Test + trace','Explain'],
  {question:'Which evidence is strongest for a guided build?',options:['A screenshot with no explanation','Working output plus trace, tests, and explanation','A copied solution'],answer:1,explanation:'The combined evidence connects implementation to understanding.'},
  'Outline the inputs, outputs, changing state, and failure cases of your guided build.',
  {title:'Paper Exam 0C + guided build',instructions:'Complete the closed exam and submit the build screenshot with a written system explanation.'},'exam'),

makeLesson('S0-W4-D1',4,'Monday','Files and data','files',
  'Data must outlive a running program when future sessions need it. Files encode information in a format that software can write, store, read, validate, and sometimes exchange.',
  'A written roster preserves team information after practice ends; memory alone disappears when the session ends.',
  ['Encode','Store','Read later'],
  {question:'Why might an app use a file?',options:['To preserve information after the app closes','To prevent all data from being read','To replace every variable'],answer:0,explanation:'Persistent storage keeps information available across executions.'},
  'Identify data in one app that must persist after the app closes.',
  {title:'Three storage examples',instructions:'Find three places where apps store information and explain why each must persist.'}),

makeLesson('S0-W4-D2',4,'Tuesday','Lists and arrays intuition','lists',
  'A list or array groups related values into an ordered collection. An index identifies a position, allowing a program to retrieve or update a particular element systematically.',
  'A volleyball lineup is an ordered collection; position numbers let the coach refer to specific places.',
  ['Collection','Index','Access / update'],
  {question:'If indexing begins at zero, what is the index of the third item?',options:['3','2','1'],answer:1,explanation:'Zero-based positions are 0, 1, 2 for the first three items.'},
  'Write a five-item list and label its zero-based indexes.',
  {title:'Indexed list',instructions:'Draw a list of ten items with indexes and show two retrievals and one update.'}),

makeLesson('S0-W4-D3',4,'Wednesday','Small systems thinking','systems-thinking',
  'A system is a set of interacting parts organized around a purpose. Engineers trace inputs, processing, state, storage, validation, human review, outputs, and failures rather than viewing a feature in isolation.',
  'A restaurant is more than its menu: orders, staff, inventory, preparation, payment, and feedback interact.',
  ['Inputs + state','Processing + validation','Outputs + review'],
  {question:'Which description identifies a system?',options:['A button is red','Orders enter, kitchen work changes inventory, payment is validated, and meals leave','The restaurant has chairs'],answer:1,explanation:'It identifies interacting parts and information flow around a purpose.'},
  'Map the Academy itself as a system, including storage and human review.',
  {title:'Small-tool system map',instructions:'Map input, processing, storage, validation, human review, and output for one small tool.'}),

makeLesson('S0-W4-D4',4,'Thursday','Project planning','project-plan',
  'A project plan converts an idea into a bounded engineering problem. It names the user, goal, inputs, outputs, essential features, constraints, risks, and evidence that will show whether the first version works.',
  'A practice plan defines the skill, athletes, time, equipment, constraints, and success measure before drills begin.',
  ['Problem + user','Scope + constraints','Success evidence'],
  {question:'Which item belongs in a useful project plan?',options:['Every possible future feature','A specific user problem and success test','Only the project color'],answer:1,explanation:'The problem and success test guide decisions and evaluation.'},
  'Write one goal, three essential features, and two constraints for your Semester 0 project.',
  {title:'Project plan',instructions:'Submit the project goal, user/problem, features, constraints, risks, and evidence of success.'}),

makeLesson('S0-W4-D5',4,'Friday','Project build session','iteration',
  'The first build should test the riskiest assumption with the smallest useful version. Record what works, what breaks, and what you learn so the next version is based on evidence.',
  'A team tests a new rotation in a controlled drill before relying on it for an entire tournament.',
  ['Build small','Test assumption','Record result'],
  {question:'What should the first version prioritize?',options:['Every possible feature','The smallest build that tests the key assumption','Perfect visual polish before function'],answer:1,explanation:'A focused first version creates useful evidence quickly.'},
  'Identify the riskiest assumption in your project and the smallest test for it.',
  {title:'First project version',instructions:'Build or outline the first version and record one working part, one broken part, and one next change.'}),

makeLesson('S0-W4-D6',4,'Saturday','Project polish and demo preparation','technical-communication',
  'A technical demo should communicate the problem, system, evidence, limitation, and next step. Polish improves clarity and reliability; it should not hide unfinished behavior.',
  'A good match review shows the play, explains the decision, names the result, and identifies what changes next.',
  ['Problem','System + evidence','Limit + next step'],
  {question:'Which demo is most credible?',options:['It claims everything is perfect','It shows what works and names a real limitation','It discusses colors without showing the system'],answer:1,explanation:'Credible engineering communication includes evidence and limitations.'},
  'Give a one-minute written demo using problem, system, evidence, limitation, and next step.',
  {title:'Demo preparation',instructions:'Prepare and rehearse a one-minute explanation of the project and verify the demonstration steps.'},'practice'),

makeLesson('S0-W4-D7',4,'Sunday','Semester 0 demo and final reflection','independent-learning',
  'Semester 0 is complete when you can operate the learning system independently: locate work, retrieve ideas, practice weak points, submit evidence, reflect honestly, and plan the next step.',
  'Graduating from preseason does not mean the athlete knows every future play; it means the training system is ready for the season.',
  ['Demonstrate system','Reflect on evidence','Plan next course'],
  {question:'What is the strongest evidence that Semester 0 worked?',options:['Every page was opened','The student can independently use the learning cycle and produce organized evidence','The dashboard looks complete'],answer:1,explanation:'Operational independence is stronger than appearance or page views.'},
  'Explain how you will use ChatGPT as professor and Codex as lab without replacing your own thinking.',
  {title:'Final project and reflection',instructions:'Submit the Academy workspace demonstration, final reflection, and one explanation of the Professor/Lab boundary.'},'exam')
];

const S0_EXAMS={
 'S0-W1-D7':[
  {q:'Which action is active recall?',options:['Reread a page','Explain from memory before checking','Highlight every definition'],answer:1},
  {q:'What makes a mental model useful?',options:['It preserves every detail','It supports prediction and can be revised','It replaces practice'],answer:1},
  {q:'Which reflection creates the clearest next action?',options:['I studied','Variables confuse me when values change, so I will trace three examples','Everything was difficult'],answer:1},
  {q:'What should deliberate practice target?',options:['A weakness shown by evidence','Only comfortable work','The longest chapter'],answer:0},
  {q:'Why does opening a lesson not prove mastery?',options:['The page may be too short','Exposure does not prove retrieval or application','The lesson needs more colors'],answer:1}
 ],
 'S0-W2-D7':[
  {q:'Computation transforms information using what?',options:['Defined operations or rules','Random decoration','Only human memory'],answer:0},
  {q:'A complete algorithm needs a stopping condition because…',options:['instructions should be longer','the procedure must know when it is finished','all inputs are identical'],answer:1},
  {q:'In a navigation app, the calculated route is usually a…',options:['input','output','variable name'],answer:1},
  {q:'What changes when a variable is updated?',options:['Its current value','The entire programming language','Every file on the computer'],answer:0},
  {q:'A conditional connects…',options:['a test to a selected action','two unrelated definitions','a file to a color'],answer:0}
 ],
 'S0-W3-D7':[
  {q:'A loop needs an update that moves toward…',options:['a stopping condition','a longer name','another file'],answer:0},
  {q:'Why use a tracing table?',options:['To record state during each step','To avoid reading conditions','To replace the program'],answer:0},
  {q:'A function packages…',options:['a reusable responsibility','every program into one line','only visual design'],answer:0},
  {q:'The first debugging step is to…',options:['change several things','state expected and actual behavior','delete the code'],answer:1},
  {q:'Code runs but produces the wrong total. This is most likely a…',options:['syntax error','logic error','missing keyboard'],answer:1}
 ],
 'S0-W4-D7':[
  {q:'Why store information in a file?',options:['To preserve it across program sessions','To eliminate all variables','To prevent later reading'],answer:0},
  {q:'With zero-based indexing, the third item has index…',options:['3','2','1'],answer:1},
  {q:'Systems thinking traces…',options:['only the interface color','interacting inputs, processing, state, validation, and outputs','one isolated button'],answer:1},
  {q:'A strong first project version should…',options:['test the riskiest assumption with a small useful build','contain every future feature','hide limitations'],answer:0},
  {q:'What is Codex’s role in the Academy?',options:['Replace the student’s reasoning','Act as a lab for implementation after the system is understood','Award mastery whenever code exists'],answer:1}
 ]
};
const S0_EXAM_TITLES={'S0-W1-D7':'Paper Exam 0A','S0-W2-D7':'Paper Exam 0B','S0-W3-D7':'Paper Exam 0C','S0-W4-D7':'Semester 0 cumulative check'};
for(const lesson of window.S0_LESSONS){if(S0_EXAMS[lesson.id])lesson.exam={title:S0_EXAM_TITLES[lesson.id],timeLimit:'20 minutes',allowedMaterials:'None unless explicitly allowed',questions:S0_EXAMS[lesson.id]}}
